[build]
  publish = "web-client"
  command = "echo 'No build step required'"

[[redirects]]
  from = "/api/*"
  to = "https://your-api-server.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
